- hosts: localhost
  gather_facts: false
  vars_files:
    - resources.yml
  tasks:
    - name: cloud_1
      gravesm.aws.resources:
        state: "{{ state | default('present') }}"
      register: cloud_1

    - debug:
        msg: "{{ cloud_1 }}"

    - name: cloud_2
      gravesm.aws.resources:
        state: "{{ state | default('present') }}"
