- hosts: localhost
  gather_facts: false
  vars_files:
    - resources.yml
  tasks:
    - name: cloud_1
      gravesm.aws.resources:
        state: "{{ state | default('present') }}"
        connection:
          profile_name: content

    - name: cloud_2
      gravesm.aws.resources:
        state: "{{ state | default('present') }}"
        connection:
          profile_name: content

    - name: cloud_3
      gravesm.kubernetes.resources:
        state: "{{ state | default('present') }}"
        connection:
          kubeconfig: ~/.kube/config
