cloud_1:
  - name: bucket_02
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ansible-declared-state-02

  - name: bucket_01
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ansible-declared-state-01
      Tags:
        - Key: otherbucket
          Value: resource:bucket_02.Properties.Arn

  - name: bucket_03
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ansible-declared-state-03

cloud_2:
  - name: bucket_01
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ansible-declared-state-04
